#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ===== MONITOR ===== #
bspc monitor DP2 -d 1
bspc monitor HDMI2 -d 2 3 4 5 6 7 8 9 10

xrandr --output HDMI2 --primary --mode 1920x1080 --rotate normal --output DP2 --mode 1680x1050 --rotate normal --left-of HDMI2

# ===== BORDERS ===== #
bspc config border_width         2
bspc config normal_border_color  "#cba6f7"
bspc config focused_border_color "#cba6f7"

# ===== WINDOW GAP ===== #
bspc config window_gap          15

# ===== OTHER STUFF ===== #
bspc config single_monocle        true
bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &

# ===== FLOATING RULES ===== #
bspc rule -a network     state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a flameshot   state=floating
bspc rule -a floating    state=floating

# ===== AUTOSTART RULES ===== #
setxkbmap it &
picom -b &
nitrogen --restore &
polybar bar1 &
polybar bar2 &
polybar bar3 &
polybar bar4 &
polybar bar5 &
polybar bar6 &

